# Generated by Django 5.0.14 on 2026-03-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('interaction', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentst',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posts', verbose_name='post_id'),
        ),
        migrations.AddField(
            model_name='commentst',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.codet', verbose_name='code_id'),
        ),
        migrations.AddField(
            model_name='liket',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posts', verbose_name='post_id'),
        ),
        migrations.AddField(
            model_name='liket',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.codet', verbose_name='code_id'),
        ),
    ]
