from enum import Enum

class ReasonCode(Enum):
    """
    ETL 파이프라인 전반에서 발생하는 실패의 원인을 정의하는 Enum.
    """
    NETWORK_ERROR = "NETWORK_ERROR"
    PROXY_ERROR = "PROXY_ERROR"
    TIMEOUT = "TIMEOUT"
    SELECTOR_MISMATCH = "SELECTOR_MISMATCH"
    BOT_DETECTED = "BOT_DETECTED"
    NOT_FOUND = "NOT_FOUND"      
    INVALID_URL = "INVALID_URL"
    INVALID_DATA_FORMAT = "INVALID_DATA_FORMAT"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    NOT_RESTAURANT_ENTITY = "NOT_RESTAURANT_ENTITY" 
    CONFLICTING_DEDUP_SIGNALS = "CONFLICTING_DEDUP_SIGNALS" 
    DB_CONNECTION_ERROR = "DB_CONNECTION_ERROR"
    DB_CONSTRAINT_VIOLATION = "DB_CONSTRAINT_VIOLATION"
    REFERENCE_INTEGRITY_VIOLATION = "REFERENCE_INTEGRITY_VIOLATION"
    UNDEFINED_CODE_DETECTED = "UNDEFINED_CODE_DETECTED" 
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    INTERNAL_PIPELINE_ERROR = "INTERNAL_PIPELINE_ERROR"

    def __str__(self):
        return self.value
