
services:
  db:
    image: postgres:16
    container_name: sk_connect
    restart: always
    environment:
      POSTGRES_DB: service       # Django의 DB_NAME과 일치
      POSTGRES_USER: user     # Django의 DB_USER와 일치
      POSTGRES_PASSWORD: password123 # Django의 DB_PASSWORD와 일치
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: