# Generated by Django 5.0.14 on 2026-03-16 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='게시글 본문')),
                ('title', models.CharField(max_length=100, verbose_name='게시글 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('post_cd', models.ForeignKey(db_column='post_cd', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_category', to='common.codet')),
                ('status_cd', models.ForeignKey(db_column='status_cd', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_status', to='common.codet')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(unique=True, verbose_name='이미지 링크')),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, to='post.posts')),
            ],
            options={
                'db_table': 'post_image',
            },
        ),
    ]
