# Generated by Django 5.0.14 on 2026-03-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='게시글 본문')),
                ('title', models.CharField(max_length=100, verbose_name='게시글 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('post_cd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_category', to='common.codet', verbose_name='카테고리 코드')),
                ('status_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_status', to='common.codet', verbose_name='상태코드')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(unique=True, verbose_name='이미지 링크')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posts', verbose_name='게시글 아이디')),
            ],
        ),
    ]
