# Generated by Django 6.0.2 on 2026-03-05 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('Image_url', models.TextField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posts', verbose_name='게시글 아이디')),
            ],
        ),
    ]
