# Generated by Django 5.0.14 on 2026-03-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurl',
            name='image_url',
            field=models.URLField(unique=True, verbose_name='이미지 링크'),
        ),
    ]
