# Generated by Django 5.0.14 on 2026-03-16 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_maps_post'),
        ('post', '0002_alter_imageurl_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='map',
            field=models.ForeignKey(blank=True, db_column='map_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.maps'),
        ),
    ]
