# Generated by Django 5.0.14 on 2026-03-19 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_menu', models.TextField(blank=True, null=True)),
                ('map', models.ForeignKey(db_column='map_id', on_delete=django.db.models.deletion.CASCADE, related_name='signature_menus', to='maps.maps')),
            ],
            options={
                'db_table': 'Food_Map',
            },
        ),
    ]
