# Generated by Django 5.0.14 on 2026-03-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMap',
            fields=[
                ('maps_ptr', models.OneToOneField(db_column='map_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maps.maps')),
                ('signature_menu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Food_Map',
            },
            bases=('maps.maps',),
        ),
    ]
