services:
  db:
    image: pgvector/pgvector:pg16
    container_name: sk_connect_db

    environment:
      POSTGRES_DB: ${SERVICE_DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/docker-entrypoint-initdb.d/data

  neo4j:
    image: neo4j:5
    container_name: sk_connect_neo4j

    environment:
      NEO4J_AUTH: neo4j/password

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
