# Generated by Django 5.0.14 on 2026-03-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeT',
            fields=[
                ('cd', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=30, unique=True)),
                ('cd_info', models.TextField(editable=False)),
                ('cd_upper', models.CharField(blank=True, editable=False, max_length=6, null=True)),
            ],
            options={
                'db_table': 'codeT',
            },
        ),
    ]
