# Generated by Django 5.0.14 on 2026-04-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codet',
            fields=[
                ('cd', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('cd_info', models.TextField()),
                ('cd_upper', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'codeT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500)),
                ('table_name', models.CharField(max_length=20)),
                ('table_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
    ]
