# Generated by Django 6.0.2 on 2026-03-05 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('signature_menu', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(unique=True)),
                ('latitude', models.FloatField()),
                ('longitutde', models.FloatField()),
                ('business_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.codet')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.posts')),
            ],
        ),
    ]
