# Generated by Django 5.0.14 on 2026-03-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('map_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('address_detail', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address_cd', models.ForeignKey(db_column='address_cd', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_maps', to='common.codet')),
                ('category', models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_maps', to='common.codet')),
                ('post', models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.posts')),
            ],
            options={
                'db_table': 'maps',
            },
        ),
    ]
