# Generated by Django 5.0.14 on 2026-03-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='post',
        ),
    ]
