# Generated by Django 5.0.14 on 2026-03-14 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu_name', models.TextField(blank=True, null=True, verbose_name='시그니처 메뉴')),
                ('map', models.ForeignKey(db_column='map_id', on_delete=django.db.models.deletion.CASCADE, related_name='map_menus', to='maps.maps')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
