# Generated by Django 5.0.14 on 2026-04-24 02:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='google_id',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
